### PR TITLE
directory.md added

### PR DESCRIPTION
**Pull request by poorvadiwan**
I created DIRECTORY.md listing all algorithms and data structures in the repository , and edited README.md

### CODE REVIEW

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Review by siriak — CHANGES_REQUESTED** [review]
After some discussion with folks who run https://the-algorithms.com, it's evident that moving directory to directory.md would break website integration, so please return it to readme.md and make your changes in place. Thanks!

**Comment by poorvadiwan** [comment]
> After some discussion with folks who run https://the-algorithms.com, it's evident that moving directory to directory.md would break website integration, so please return it to readme.md and make your changes in place. Thanks!

Okay, I will make the requisite changes.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by poorvadiwan** [comment]
Thanks for being so patient and nice!!

**Pull request merged**
