### PR TITLE
Migrate Project to .NET 8: Update Target Framework.

### PR DESCRIPTION
**Pull request by gmottajr**
Migration to .NET 8:  .csproj files are being updated.
- \C-Sharp\Algorithms\Algorithms.csproj
- \C-Sharp\Algorithms.Tests\Algorithms.Tests.csproj
- \C-Sharp\DataStructures\DataStructures.csproj
- \C-Sharp\DataStructures.Tests\DataStructures.Tests.csproj
- \C-Sharp\Utilities\Utilities.csproj
- \C-Sharp\Utilities.Tests\Utilities.Tests.csproj

**Please let me know whether or not it would be necessary to create new unit tests for this change.**

### **Motivation and Context**
Github issue #425: Proposed to migrate to .NET 8 to use the latest features of .NET ecosystem. It was requested to perform the changes in a few PRs to make them smaller and easier to review. This is the one only  meant to update .NET version.

- [X] I have performed a self-review of my code
- [X] My code follows the style guidelines of this project
- [X] All existing unit tests have been executed, and all have passed successfully.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Comments in areas I changed are up to date
- [ ] I have added comments to hard-to-understand areas of my code
- [X] I have made corresponding changes to the README.md

### CODE REVIEW

**Comment by siriak** [comment]
Please also update .NET version in ci.yml

**Comment by gmottajr** [comment]
Sure, done!

**Comment by siriak** [comment]
Please fix Codacy issues. Codecov is fine, I can merge with that.

**Comment by gmottajr** [comment]
I'm not getting any issue. Perhaps I'm going to ne you showing me what you see.
Nothing shows up to be fixed here so far.
image

**Comment by siriak** [comment]
They are here. You can click on Details to see details.
image

**Comment by gmottajr** [comment]
Gotcha!
Changed as per request.
Thank you for the clarification.

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by gmottajr** [comment]
You are welcome!
I'm going to jump to the next group of changes, be right back soon. Thank you very much!

**Pull request merged**
