### PR TITLE
A* Improvements

### PR DESCRIPTION
**Pull request by ByteChkR**
First Contribution in OpenSource for me. Flame me if i fucked up.
I improved the A* algorithm with better readable variable names and other improvements
Added Priority Queue
Added N Dimensional Vector
Implemented Traversal Costs
Added Different Search Heuristics(A*, Dijkstra, Greedy)
For some reason the Test Projects were set to .net 2.2(that do not work with my sdk) NO OTHER CHANGES TO TEST PROJECTS

### CODE REVIEW

**Comment by siriak** [comment]
First things first, thank you for your time! A couple of suggestions:

**Comment by siriak** [comment]
First things first, thank you for your time! New people are always welcome here. A couple of suggestions:
- Make separate pull requests for separate features (one for each algorithm and data structure). It will be easier to read this way.
- Address codacy-bot comments (we have some sort of code style here and bot helps to adhere to it). Fix issues or comment if the bot suggests something stupid, unfortunately it happens a lot.
I'll ponder on your code when I have free time later this week.

**Comment by siriak** [comment]
Hey man, how is it going? If you don't have time to fix the issues any time soon, we can accept this PR as is and fix them afterwards. Let me know what you think.

**Comment by ByteChkR** [comment]
> 
> 
> Hey man, how is it going? If you don't have time to fix the issues any time soon, we can accept this PR as is and fix them afterwards. Let me know what you think.

Sorry, I am not at home at the moment sadly. I'll be back on thursday from vacations. I will fix stuff asap as soon as i am available. No worries, I am not dissapeared or something ;). Just a little busy having vacations and writing applications.
Kind regards
Byte

**Comment by siriak** [comment]
Could you update this branch so that I can merge changes in case they are ready? It seems to me that CI broke for some reason.

**Pull request merged**
