### PR TITLE
Add Unit Test for Negative Hash Codes in HashTable and Note on TimSort Test Limitations

### PR DESCRIPTION
**Pull request by Kalkwst**
## Description

This PR introduces a new unit test to ensure that our custom `HashTable` implementation correctly handles keys with negative hash codes. Additionally, it includes a discussion on the challenges and limitations of testing certain aspects of the TimSort algorithm due to their deep integration within the private sections of the codebase.

### Key Changes

1. **Unit Test for Negative Hash Codes:**
   - **New Test:** `Test_NegativeHashKey_ReturnsCorrectValue`
     - **Purpose:** Validates that the `HashTable` can handle keys that generate negative hash codes, ensuring that the data structure remains robust under such conditions.
     - **Implementation:** The test creates a `NegativeHashKey` class that generates negative hash codes, adds a key-value pair to the `HashTable`, and verifies that the value can be retrieved correctly using the same key.

2. **Discussion on TimSort Test Limitations:**
   - **Private Method:** `FinalizeMerge(TimChunk<T> left, TimChunk<T> right, int dest)`
     - The condition `left.Remaining == 0` should theoretically never occur if the TimSort algorithm is functioning correctly. This would imply that the left chunk has been entirely consumed before this method is called, indicating a potential bug in the merge logic or an error in the comparison method that leads to an incorrect merge sequence.
     - Writing tests to cover this scenario, as well as other deep parts of the TimSort implementation, is challenging because these methods are private and tightly coupled with the internal logic of the algorithm. To effectively test these edge cases, significant refactoring would be required to expose these methods or alter the structure of the code, which is disproportionate to the value gained from these minor tests.

   - **Note on Coverage:** Other uncovered methods in TimSort are also deeply embedded within the call chain, making it difficult to create the conditions necessary to trigger them in a controlled testing environment. Given the complexity and potential for unintended side effects, comprehensive testing of these methods would likely require a broader refactoring effort that extends beyond the scope of this PR.

### Future Considerations

- **Refactoring for Testability:** While it is not addressed in this PR, it may be worth considering a future refactor of the TimSort implementation to make it more testable. This could involve exposing key methods or breaking down complex functions into more testable components.
---

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Comments in areas I changed are up to date
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have made corresponding changes to the README.md

### CODE REVIEW

**Comment by siriak** [comment]
Could you then remove the check for `left.Remaining == 0` in FinalizeMerge? If it's impossible based on the algorithm, we shouldn't validate it because it's a private method. We can guarantee that it won't be called with 0.

To find test cases for other methods, you can do fuzz testing with random arrays and set a breakpoint in the place you want to test. When the breakpoint is hit, you can see arguments that were passed to tim sort and add a test case with these arguments.

Anyway, this PR looks good and I can merge it as-is. Let me know if I need to merge it in the current state or you want to make Tim sort changes here.

**Comment by Kalkwst** [comment]
Let's keep this PR for the time, I am working on a solution but it is not ready yet

**Comment by Kalkwst** [comment]
I believe that with this PR, the unit tests should now be significantly less flaky. A lot of the internal state management has been improved, which allows for more consistent and controlled testing. This has helped to stabilize some of the previously unreliable tests.

However, it’s important to note that while the internal state is now more manageable and testable, the overall TimSort algorithm remains quite complex and difficult to fully understand, especially from an educational standpoint, which is the goal of this repository.

Given that Hacktoberfest is approaching, I recommend we address a more comprehensive refactor or rewrite of the entire TimSort algorithm at a later point in time. A future PR could focus on breaking down the algorithm further, making it easier to follow and understand, while still retaining its educational value.

For now, this PR achieves its intended purpose, stabilizing the current implementation and improving testability. We can create a follow-up PR after Hacktoberfest to refactor the entire TimSort algorithm in a more educational and maintainable way.

**Comment by Kalkwst** [comment]
I’ve done my best to improve the testability of the TimSorter class by addressing the internal state management and making parts of the code more modular and testable. This PR resolves some or most of the issues around flakiness and testability.

However, I have to note that the overall complexity of the class remains high, making it difficult to understand—especially considering that this repository is intended to be educational. The current implementation, while functional, is still not very accessible for learners or contributors who may want to understand and learn from the code.

Given that, while this PR improves things, we should seriously consider rewriting or refactoring the entire TimSort algorithm to make it clearer, more maintainable, and educationally valuable. I suggest addressing this after Hacktoberfest, as this PR achieves its short-term goals, but a more extensive rewrite would be better suited for a later effort.

**Comment by siriak** [comment]
It's much better now indeed. If you know how to improve TimSorter, feel free to do that.

**Review by siriak — APPROVED** [review]

**Pull request merged**
