### PR TITLE
Use random pivot for quicksort

### PR DESCRIPTION
**Pull request by eugbaranov**
It is important to use random pivot in quicksort in order to achieve average `O (n log n)` time complexity as otherwise pathological inputs can cause it to run in `O (n^2)`.

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have made corresponding changes to the comments
- [ ] I have made corresponding changes to the README.md

### CODE REVIEW

**Review by siriak — CHANGES_REQUESTED** [review]
> It is important to use random pivot in quicksort in order to achieve average O (n log n) time complexity as otherwise pathological inputs can cause it to run in O (n^2).

Well, pathological inputs can still cause it to run in O(n^2) even with random pivot. We won't be able to create input that causes O(n^2) all the time, but they will still exist, so worst-case scenario O(n^2) still holds. And there are cases where algorithms must be deterministic, so I wouldn't say that a random pivot is better than a deterministic one or vise versa.

So, why not have both? Maybe you could do an abstract quick sorter that has an abstract method SelectPivot(int left, int right) and 2 descendants MiddlePointQuickSorter and RandomPivotQuickSorter? That way we could have both versions of the algorithm, what's your take on that?

**Comment by eugbaranov** [comment]
True, with random pivot there is still a probability to run in `O (n^2)` although the bigger the input the less likely it is to end up with the worst case (akin to flipping coin head many times in a row).

That's said I think it would be good to have a way of using a different pivot as many quicksort enhancements are based on pivot selection.

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MedianOfThreeQuickSorter.cs  6
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MiddlePointQuickSorter.cs  1
- Algorithms/Sorters/Comparison/RandomPivotQuickSorter.cs  1
         

Clones added
============
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6339479&bid=20592950)

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MedianOfThreeQuickSorter.cs  6
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/RandomPivotQuickSorter.cs  1
- Algorithms/Sorters/Comparison/MiddlePointQuickSorter.cs  1
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  1
         

Clones added
============
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6339479&bid=20592950)

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  1
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MedianOfThreeQuickSorter.cs  6
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/RandomPivotQuickSorter.cs  1
- Algorithms/Sorters/Comparison/MiddlePointQuickSorter.cs  1
         

Clones added
============
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6339479&bid=20592950)

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MedianOfThreeQuickSorter.cs  6
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MiddlePointQuickSorter.cs  1
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/RandomPivotQuickSorter.cs  1
         

Clones added
============
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6339479&bid=20592950)

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms/Sorters/Comparison/RandomPivotQuickSorter.cs  1
- Algorithms/Sorters/Comparison/MedianOfThreeQuickSorter.cs  6
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MiddlePointQuickSorter.cs  1
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  1
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  1
         

Clones added
============
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6339479&bid=20592950)

**Review by siriak — DISMISSED** [review]
Looks good, could you update Readme.md accordingly and I'll merge?

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  1
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/MiddlePointQuickSorter.cs  1
- Algorithms/Sorters/Comparison/RandomPivotQuickSorter.cs  1
- Algorithms/Sorters/Comparison/MedianOfThreeQuickSorter.cs  6
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  1
         

Clones added
============
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6339479&bid=20592950)

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- Algorithms/Sorters/Comparison/MiddlePointQuickSorter.cs  1
- Algorithms/Sorters/Comparison/MedianOfThreeQuickSorter.cs  6
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  1
- Algorithms/Sorters/Comparison/RandomPivotQuickSorter.cs  1
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  1
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  1
         

Clones added
============
- Algorithms.Tests/Sorters/Comparison/RandomPivotQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/MiddlePointQuickSorterTests.cs  2
- Algorithms.Tests/Sorters/Comparison/MedianOfThreeQuickSorterTests.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6339479&bid=20592950)

**Review by siriak — APPROVED** [review]
Thanks!

**Pull request merged**
