### PR TITLE
Add Sorted List Data Structure

### PR DESCRIPTION
**Pull request by rohansp**
Hi,
I have implemented the Sorted List Data Structure.

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have made corresponding changes to the comments
- [x] I have made corresponding changes to the README.md

### CODE REVIEW

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- DataStructures.Tests/Helpers/RandomHelper.cs  2
- DataStructures.Tests/SortedListTests.cs  1
- DataStructures.Tests/Helpers/IntComparer.cs  1
- DataStructures/SortedList/SortedList.cs  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6367347&bid=20662528)

**Comment by siriak** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- DataStructures.Tests/Helpers/IntComparer.cs  1
- DataStructures.Tests/SortedListTests.cs  1
- DataStructures/SortedList/SortedList.cs  5
- DataStructures.Tests/Helpers/RandomHelper.cs  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/siriak/C-Sharp/pullRequest?prid=6367347&bid=20662528)

**Review by siriak — CHANGES_REQUESTED** [review]
It's not the Sorted List data structure because it doesn't contain any fields at all. For example [here](https://ece.uwaterloo.ca/~dwharder/aads/Abstract_data_types/Linear_ordering/Sorted_list/) you can find some properties of Sorted List. Insertion, removal, and search by criteria are some of the required operations.

**Comment by siriak** [comment]
A lot of additional changes are required, so I'm closing this PR at the moment, feel free to open a new one when the feedback is addressed

**Comment by rohansp** [comment]
sure

**Comment by rohansp** [comment]
So, this doesn't qualify as valid pull request under Hacktoberfest? It didn't merge.

**Comment by siriak** [comment]
No, it doesn't

**Pull request closed without merging**
