### PR TITLE
Recommender Systems by User-based Collaborative Filtering

### PR DESCRIPTION
**Pull request by ngtduc693**
This PR introduces a User-based Collaborative Filtering algorithm implemented in C#. The algorithm predicts a user's rating for a given item based on ratings from other users with similar preferences. The main components of this PR include

**CollaborativeFiltering** included:

- **CalculateSimilarity**: Computes the similarity between two users based on their shared item ratings using the Pearson correlation coefficient.
- **PredictRating**: Using ratings from other users who have rated the same item, it forecasts a target user's rating for a particular item. The prediction is a weighted sum determined by user similarity. 

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Comments in areas I changed are up to date
- [x] I have added comments to hard-to-understand areas of my code
- [x] I have made corresponding changes to the README.md

### CODE REVIEW

**Comment by ngtduc693** [comment]
First time attending hacktoberfest 2024, and this is my first PR, I hope everything goes well 😃

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by siriak** [comment]
Please increase test coverage

**Comment by ngtduc693** [comment]
Hi @siriak , I just added some test cases to increase the test coverage percent

Thanks for your help to review

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
