### PR TITLE
Added BalancedParenthesesChecker.cs, NextGreaterElement.cs and ReverseStack.cs

### PR DESCRIPTION
**Pull request by mohit-gogitter**
### Description
I have created **stack-based** utility classes in **C#** that can be used by other developers in their solutions. 
This utility provides commonly used operations related to stacks, which can be beneficial for solving various problems such as expression evaluations, balanced parentheses, or maintaining a history of operations.

These classes can be used to perform below stack-related operations:
**Next Greater Element**: Given an array, find the next greater element for each element in the array.
**Balanced Parentheses Checker**: A utility to check whether a given expression has balanced parentheses.
**Reverse a Stack**: Function to reverse a stack.

### CheckList:
- I have performed a self-review of my code
- My code follows the style guidelines of this project
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Comments in areas I changed are up to date
- I have added comments to hard-to-understand areas of my code
- I have made corresponding changes to the README.md

### CODE REVIEW

**Comment by siriak** [comment]
Please put separate algorithms in separate classes with descriptive names and check if they are already implemented in the repository

**Comment by mohit-gogitter** [comment]
@siriak  As suggested, i have created separate classes for algorithms and removed redundant code

**Review by siriak — CHANGES_REQUESTED** [review]
Please move them to algorithms project because they are not data structures, they only use stack data structure, add tests, and fix Codacy and other build checks

**Comment by mohit-gogitter** [comment]
@siriak Moved to Algorithms project, Added Tests, fixed codacy and build issues

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
