### PR TITLE
remove unnecessary array loop

### PR DESCRIPTION
**Pull request by JoaoVictor6**
This pull request is for issue #372. I did not add new tests because the changes do not implement a new feature, only remove an unnecessary structure to simplify the code

- [x] I have performed a self-review of my code
- [x] My code follows the style guidelines of this project
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Comments in areas I changed are up to date
- [ ] I have added comments to hard-to-understand areas of my code
- [ ] I have made corresponding changes to the README.md

### CODE REVIEW

**Comment by JoaoVictor6** [comment]
In this case, it's necessary for all checklist items should be marked?

**Review by siriak — APPROVED** [review]
Looks good, thanks!

**Comment by siriak** [comment]
The checklist doesn't matter as long as you've read it :)

**Comment by siriak** [comment]
Hmm, it seems that this PR fell through the cracks for some reason. I apologize.

**Pull request merged**
