### PR TITLE
Update DIRECTORY.md for website

### PR DESCRIPTION
**Pull request by maltejur**
- rename `Sorts>Comparison>Selection` to `Sorts>Comparison>Selection Sort` 
- rename `Sorts>Comparison>Shell` to `Sorts>Comparison>Shell Sort`
- ~~remove `Searches>Knuth–Morris–Pratt` since it doesn't seem to exist~~ fix `Knuth–Morris–Pratt` url
- rename `NYSIISEncoder` to `NysiisEncoder`
- remove `Singular Vector Decomposition` and replace it with `Thin Singular Vector Decomposition`
- remove `//` from url in `Mandelbrot`, `Koch Snowflake` and `RGB-HSV Conversion`
- fix url for `Min-Max Heap`
- fix url for `Binary Heap`

@siriak would it also possible for you to add me as a code owner for the `DIRECTORY.md`, so I can push such small changes directly?

### CODE REVIEW

**Review by siriak — DISMISSED** [review]
I can add you as a code owner for sure, but I think it won't allow you to push this file. You will be just added to reviewers when someone changes it :)

**Comment by siriak** [comment]
The master branch is protected, that's why you cannot push (in fact, no one can). This is a good thing. Just ping me in discord if you need to merge something asap, I'll try to be responsive.

**Comment by siriak** [comment]
BTW, Knuth–Morris–Pratt exists, just in String algorithms. Could you update DIRECTORY and README in this PR?

**Comment by maltejur** [comment]
> I can add you as a code owner for sure, but I think it won't allow you to push this file. You will be just added to reviewers when someone changes it :)

Ah ok, not a big problem

> BTW, Knuth–Morris–Pratt exists, just in String algorithms. Could you update DIRECTORY and README in this PR?

I've added Knuth–Morris–Pratt again and updated the REDME from the DIRECTORY. Do you know if there were any algorithms in the README that weren't in the DIRECTORY that I might have missed?

**Review by siriak — APPROVED** [review]

**Review by siriak — COMMENTED** [review]
Why have you changed the links in README? I'd prefer relative links as they used to be. This way they work locally in IDE.

**Comment by siriak** [comment]
BTW, is DIRECTORY.md still required?

**Comment by siriak** [comment]
As for the algorithms that weren't in DIRECTORY but were in README, I see there are 111 additions and 115 deletions in README, so something might be missing.

**Comment by maltejur** [comment]
> BTW, is DIRECTORY.md still required?

For all the other repositories, no, but since we didn't find a good way to automate this repo it is a special case now and the `DIRECTORY.md` is still required.

**Comment by maltejur** [comment]
> Why have you changed the links in README? I'd prefer relative links as they used to be. This way they work locally in IDE.

Ah didn't know that, I just copied everything from the directory. I'll change it.



> As for the algorithms that weren't in DIRECTORY but were in README, I see there are 111 additions and 115 deletions in README, so something might be missing.

Okay I am also going to look for that

**Comment by maltejur** [comment]
> 111 additions and 115 deletions in README

Didn't find anything missing, seems to just be removed empty lines.

Another thing. The readme also had links on the categories. Should I add them again, or is it ok if they are missing?

**Comment by siriak** [comment]
I'd prefer to keep them because they allow opening a folder and examining everything inside it.

**Comment by siriak** [comment]
It seems Fibonacci Heap is missing, could you verify?

**Comment by maltejur** [comment]
> It seems Fibonacci Heap is missing, could you verify?

Yes, I missed that one, fixed it

I've also added the links again to the folders. The two files should be the same now content wise. Now, if every pr updates them correctly, we hopefully won't have to touch them again.

Also it probably really is a good thing I don't have push access, with all the things that were missing here.

**Review by siriak — APPROVED** [review]

**Pull request merged**
